### ISSUE TITLE
Thoughts on `data-components`?

### ISSUE THREAD

**Issue by rafaelrinaldi** [Mercateo/component-check#19]
I've been working on this tiny library called [`data-components`](https://github.com/rafaelrinaldi/data-components) that's basically a simple component structure for non SPA projects.

Let me know your thoughts and if you think it belongs here.

Cheers and congrats for gathering so much great material here!

**Comment by donaldpipowitch** [comment]
Hi, I'm sorry. I don't think I have enough time currently to look deeper into your framework. I'm sorry.

**Comment by rafaelrinaldi** [comment]
@donaldpipowitch No worries.
